package com.example.ui.theme

object Localization {
    private val arMap = mapOf(
        "app_title" to "المالي الذكي برو",
        "developer_credit" to "تطوير م/ محمد صبري",
        "developer_credit_sub" to "مطور برمجيات عالمي وخبير في تجربة المستخدم",
        "visit_telegram" to "زيارة قناة المطور",
        "telegram_link" to "https://t.me/Mohammedsabrymodder",
        "copyright" to "© جميع الحقوق محفوظة - تطوير م/ محمد صبري",
        "onboarding_1_title" to "إدارة المصروفات",
        "onboarding_1_desc" to "تتبع مصروفاتك اليومية وصنفها بدقة فائقة للتحكم في ميزانيتك.",
        "onboarding_2_title" to "تحقيق الأهداف",
        "onboarding_2_desc" to "أنشئ أهدافاً ادخارية مخصصة وتابع نسبة تقدمك خطوة بخطوة.",
        "onboarding_3_title" to "متابعة الدخل والادخار",
        "onboarding_3_desc" to "راقب مصادر دخلك وحلل عاداتك المالية للوصول إلى الحرية المالية.",
        "dashboard" to "الرئيسية",
        "expenses" to "المصروفات",
        "income" to "الدخل",
        "goals" to "الأهداف",
        "reports" to "التقارير",
        "analytics" to "الإحصائيات",
        "settings" to "الإعدادات",
        "about" to "عن التطبيق",
        "telegram_label" to "📢 قناة المطور",
        "current_balance" to "الرصيد الحالي",
        "total_income" to "إجمالي الدخل",
        "total_expenses" to "إجمالي المصروفات",
        "savings_rate" to "نسبة الادخار",
        "daily_spending" to "الإنفاق اليومي",
        "monthly_spending" to "الإنفاق الشهري",
        "recent_transactions" to "آخر العمليات",
        "amount" to "المبلغ",
        "category" to "التصنيف",
        "note" to "ملاحظة (اختياري)",
        "currency" to "العملة",
        "add_expense" to "إضافة مصروف",
        "add_income" to "إضافة دخل",
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "edit" to "تعديل",
        "search" to "بحث في المعاملات...",
        "all" to "الكل",
        "custom_categories" to "تصنيفات مخصصة",
        "weekly" to "أسبوعي",
        "monthly" to "شهري",
        "budget_limit" to "الميزانية المحددة",
        "budget_warning" to "تنبيه: اقتربت من الحد الأقصى للميزانية!",
        "budget_exceeded" to "تنبيه: لقد تجاوزت الميزانية المحددة!",
        "saving_goals" to "أهداف الادخار",
        "goal_name" to "اسم الهدف",
        "target_amount" to "المبلغ المطلوب",
        "current_amount" to "المبلغ الحالي",
        "add_goal" to "إضافة هدف جديد",
        "add_progress" to "إضافة مبلغ للهدف",
        "target_date" to "التاريخ المستهدف",
        "xp_points" to "نقاط XP",
        "level" to "المستوى",
        "achievements" to "شارات الإنجاز",
        "notifications" to "التنبيهات",
        "security" to "الأمان",
        "pin_security" to "قفل التطبيق برقم سري (PIN)",
        "fingerprint" to "بصمة الإصبع / الوجه",
        "change_language" to "تغيير اللغة",
        "change_theme" to "تغيير الثيم",
        "backup" to "نسخة احتياطية محلياً",
        "restore" to "استعادة النسخة الاحتياطية",
        "manage_notif" to "إدارة الإشعارات المحلية",
        "about_content" to "تطبيق Smart Finance Tracker Pro هو شريكك الذكي لإدارة شؤونك المالية الشخصية بأسلوب عصري واحترافي مستوحى من البنوك العالمية.",
        "app_version" to "الإصدار 1.0.0",
        "pin_prompt" to "أدخل الرمز السري المكون من 4 أرقام للدخول",
        "empty_transactions" to "لا توجد معاملات بعد. ابدأ بإضافة مصروف أو دخل!",
        "empty_goals" to "لا توجد أهداف ادخارية حالياً. خطط لمستقبلك الآن!",
        "empty_budgets" to "لم يتم تعيين ميزانيات بعد.",
        "food" to "الطعام",
        "transport" to "المواصلات",
        "education" to "الدراسة",
        "shopping" to "التسوق",
        "bills" to "الفواتير",
        "health" to "الصحة",
        "entertainment" to "الترفيه",
        "family" to "الأسرة",
        "work" to "العمل",
        "other" to "أخرى",
        "salary" to "راتب",
        "freelance" to "عمل حر",
        "investment" to "استثمار",
        "bonus" to "مكافأة",
        "project" to "مشروع خاص",
        "add_budget" to "تعيين ميزانية",
        "view_all" to "عرض الكل",
        "export_pdf" to "تصدير كتقرير PDF",
        "export_excel" to "تصدير كملف Excel",
        "xp" to "نقاط الخبرة",
        "completed_goals" to "الأهداف المكتملة",
        "unlocked" to "مكتمل",
        "locked" to "مغلق",
        "export_success" to "تم تصدير التقرير بنجاح وحفظه محلياً!",
        "backup_success" to "تم إنشاء نسخة احتياطية مشفرة بنجاح!",
        "restore_success" to "تم استعادة البيانات والنسخة الاحتياطية بنجاح!",
        "profile" to "الملف الشخصي",
        "daily_report" to "تقرير يومي",
        "weekly_report" to "تقرير أسبوعي",
        "monthly_report" to "تقرير شهري",
        "yearly_report" to "تقرير سنوي",
        "spending_analytics" to "تحليلات الإنفاق",
        "saving_trend" to "اتجاهات الادخار",
        "total_transactions" to "عدد العمليات"
    )

    private val enMap = mapOf(
        "app_title" to "Smart Finance Pro",
        "developer_credit" to "Dev by Eng. Mohammed Sabry",
        "developer_credit_sub" to "Global Software Engineer & UI/UX Expert",
        "visit_telegram" to "Visit Developer Channel",
        "telegram_link" to "https://t.me/Mohammedsabrymodder",
        "copyright" to "© All Rights Reserved - Dev by Eng. Mohammed Sabry",
        "onboarding_1_title" to "Expense Management",
        "onboarding_1_desc" to "Track your daily expenses and categorize them precisely for smart budgeting.",
        "onboarding_2_title" to "Achieve Financial Goals",
        "onboarding_2_desc" to "Create savings goals and track your milestone progress step by step.",
        "onboarding_3_title" to "Track Income & Savings",
        "onboarding_3_desc" to "Monitor your income channels and analyze monthly savings to reach freedom.",
        "dashboard" to "Dashboard",
        "expenses" to "Expenses",
        "income" to "Income",
        "goals" to "Goals",
        "reports" to "Reports",
        "analytics" to "Analytics",
        "settings" to "Settings",
        "about" to "About",
        "telegram_label" to "📢 Developer Channel",
        "current_balance" to "Current Balance",
        "total_income" to "Total Income",
        "total_expenses" to "Total Expenses",
        "savings_rate" to "Savings Rate",
        "daily_spending" to "Daily Spending",
        "monthly_spending" to "Monthly Spending",
        "recent_transactions" to "Recent Transactions",
        "amount" to "Amount",
        "category" to "Category",
        "note" to "Note (Optional)",
        "currency" to "Currency",
        "add_expense" to "Add Expense",
        "add_income" to "Add Income",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "search" to "Search transactions...",
        "all" to "All",
        "custom_categories" to "Custom Categories",
        "weekly" to "Weekly",
        "monthly" to "Monthly",
        "budget_limit" to "Budget Limit",
        "budget_warning" to "Warning: Approaching your budget limit!",
        "budget_exceeded" to "Warning: Budget Limit Exceeded!",
        "saving_goals" to "Savings Goals",
        "goal_name" to "Goal Name",
        "target_amount" to "Target Amount",
        "current_amount" to "Current Amount",
        "add_goal" to "Add New Goal",
        "add_progress" to "Add Money",
        "target_date" to "Target Date",
        "xp_points" to "XP Points",
        "level" to "Level",
        "achievements" to "Achievements",
        "notifications" to "Notifications",
        "security" to "Security",
        "pin_security" to "App PIN Security Lock",
        "fingerprint" to "Biometric/Face Unlock",
        "change_language" to "Change Language",
        "change_theme" to "Change Theme",
        "backup" to "Local Backup",
        "restore" to "Restore Backup",
        "manage_notif" to "Local Notifications",
        "about_content" to "Smart Finance Tracker Pro is your intelligent companion to manage personal finances elegantly, inspired by premium global challenger banks.",
        "app_version" to "Version 1.0.0",
        "pin_prompt" to "Enter 4-Digit PIN code to continue",
        "empty_transactions" to "No transactions yet. Start by adding some income or expenses!",
        "empty_goals" to "No active goals. Plan your future purchases now!",
        "empty_budgets" to "No budgets set yet.",
        "food" to "Food",
        "transport" to "Transportation",
        "education" to "Education",
        "shopping" to "Shopping",
        "bills" to "Bills",
        "health" to "Health",
        "entertainment" to "Entertainment",
        "family" to "Family",
        "work" to "Work",
        "other" to "Other",
        "salary" to "Salary",
        "freelance" to "Freelance",
        "investment" to "Investment",
        "bonus" to "Bonus",
        "project" to "Side Project",
        "add_budget" to "Set Budget",
        "view_all" to "View All",
        "export_pdf" to "Export as PDF Report",
        "export_excel" to "Export as Excel Sheet",
        "xp" to "XP Points",
        "completed_goals" to "Completed Goals",
        "unlocked" to "Unlocked",
        "locked" to "Locked",
        "export_success" to "Report exported successfully and saved locally!",
        "backup_success" to "Encrypted backup created successfully!",
        "restore_success" to "Backup restored successfully!",
        "profile" to "Profile",
        "daily_report" to "Daily Report",
        "weekly_report" to "Weekly Report",
        "monthly_report" to "Monthly Report",
        "yearly_report" to "Yearly Report",
        "spending_analytics" to "Spending Analytics",
        "saving_trend" to "Saving Trend",
        "total_transactions" to "Transactions Count"
    )

    fun get(key: String, lang: String): String {
        return if (lang == "ar") {
            arMap[key] ?: key
        } else {
            enMap[key] ?: key
        }
    }
}
